### ISSUE TITLE
User field export and import is broken

### ISSUE THREAD

**Issue by nordentwickler** [ssplugin/ss-user-import-export#2]
Hello there,

i'm trying to export and import users with your plugin. 

1. the user field selection on the export function is not showing up
2. it is not possible to map the user fields on the import as well

Craft CMS version: 3.4.28.1

The csv-example on the documentation is a broken image. 

Could you please help?

Kind regards
Marten

**Comment by ssplugin** [comment]
@nordentwickler 

**The csv-example on the documentation is a broken image.**
>> We have added CSV example format. 

**1. the user field selection on the export function is not showing up.**
>> I guess your user field type is different because only below user field exportable:
      [Exportable fieldType: 'Plain Text', 'Radio Buttons', 'Dropdown', 'Lightswitch', 'Email', 'URL' and 'Number']
 >>https://nimb.ws/SNhOig

**2. it is not possible to map the user fields on the import as well**
>> if you have added field data in the CSV file then you can able to import field data as well. But only below field supported
      [Importable fieldType: 'Plain Text', 'Radio Buttons', 'Dropdown', 'Lightswitch', 'Email', 'URL' and 'Number']
>>https://nimb.ws/TjkrVK

Thanks.

**Comment by c-baeumer** [comment]
Same issue here!

I think the problem is the way the user fields are filtered in the templates.

    {% set fieldType = {
        'Plain Text':'Plain Text', [...]
    } %}

    {% for field in fields %}
        {% if field.displayName in fieldType|keys %}

            [...]        

        {% endif %}
    {% endfor %}`

To display only the types defined in `fieldType`, the `field.displayName` is compared with the keys from `fieldType`. 

However, this is language dependent! If a language other than english is set for the backend user, the comparison fails. I think it would be better to use the class name instead of the display name, because it is language independent:

Example (for plain text field):

<table>
    <tr>
        <th>User language</th>
        <th>Display name</th>
        <th>Class name</th>
    </tr>
    <tr>
        <td>english (en)</td>
        <td>Plain Text</td>
        <td>craft\\fields\\PlainText</td>
    </tr>
    <tr>
        <td>german (de)</td>
        <td>Reiner Text</td>
        <td>craft\\fields\\PlainText</td>
    </tr>
</table> 

So changing the code to

    {% set fieldType = {
        'craft\\fields\\PlainText':'Plain Text', [...] 
    } %}

    {% for field in fields %}
        {% if field.className in fieldType|keys %}
        
            [...]        

        {% endif %}
    {% endfor %}`

would resolve this issue.

**Comment by nordentwickler** [comment]
Now we used FeedMe instead.

**Comment by ssplugin** [comment]
@nordentwickler 

We have updated our plugin for this concerned.
Now whatever language user selected they can able to map fields.

Thanks for your suggestion.
