### ISSUE TITLE
How to import old password 

### ISSUE THREAD

**Issue by parwinderD4D** [ssplugin/ss-user-import-export#8]
Hi Team,

I am facing an issue while import/export users we want to export and import user passwords as well, I have to follow the steps which you have mentioned under the documents, but no email send to users to reset the password, If I  select **Send Activation mail**? then mail sends to users but not the password-reset.

could you please let us know how I can export / import passwords in an excel sheet?

Looking forward.

Thanks
Parwinder

**Comment by ssplugin** [comment]
@parwinderD4D 
**Export:**
You can not export users' passwords. 

**Import:**
If you need to import a password then add the **"password"** column in the CSV file. After a while of field mapping, you must select the password column against the password field.

**no email send to users to reset the password**
If you choose the password column against the password field then not need to reset the password because the password is already set as per your CSV file. 

 **If I select Send Activation mail? then mail sends to users but not the password-reset.**
In the activation mail, you have found URL of activation account

**Comment by parwinderD4D** [comment]
Let me explain what I try to want now,

I have a live site that I have set up on the development server as we want to upgrade and some new modules under it, we have already done all the new work, and meanwhile, new users register on live website, approx more the 1k, now the thing is we want to import all new user on development site, so that when we point the DNS of the old server to the development server,
So we want when we import all the new users they will get email notifications to reset their password on the new site.
Could you please guide me on how we can do this?

One thing more is there any way to import and export users assigned Category e.g [ Matrix Fields which have Typed is Categories?
Please check the screenshot for more details.
![image](https://user-images.githubusercontent.com/46927214/130288144-ca5281d9-938e-409f-9f4f-5a2c37c7998a.png)

Looking forward

Parwinder

**Comment by ssplugin** [comment]
@parwinderD4D 
**Could you please guide me on how we can do this?**
The first thing is not to reset their password because the password has been not set yet.
You need to follow below steps:
1. Import CSV file first.
2. Make sure **Status** value should be "**active**" or "**1**" in the CSV file.
3. Map all the fields correctly from the field mapping page.
4. You should select **Send Activation mail** value **yes**?
5. Most important thing is in your Development server site Email configuration working properly. (Test it first).

As per our suggestion, You need to create a CSV file with only one user and check everything working, If so then import all the users.

**One thing more is there any way to import and export users assigned Category**
No, Currently Matrix field is not possible to export or import.

In Craft cms Control panel "utilities" > "System Messages" > When someone creates an account:
Check to Activate your account "link" variable added or not
https://nimb.ws/koLlz3

 If you are not able to send activation mail with a password set link then feel free to provide your admin and FTP details to our contact email ssplugins.seeders@gmail.com

**Comment by parwinderD4D** [comment]
Thanks for the details steps.

**No, Currently Matrix field is not possible to export or import.**
-- Do you have any idea how I can import the category, If we just set manually `assignedCategoryField `values in CSV File ?
any documentation, code or syntax will help for me,  as I have checked  this `assignedCategoryField `is already work on user profile update page. but I am not able to  find it how we can do it while Import users Data.

Looking forward.
Parwinder

**Comment by ssplugin** [comment]
@parwinderD4D 
 **I have checked this assignedCategoryField is already worked on the user profile update page.**
Yes, the User profile update page handle by craft cms default UsersController.
But our plugin builds with a custom method so that we are not allowed this field.

You can manually do that task or if you can able to custom code by yourself.
If you have any idea then feel free to share with us or make a pull request with the plugin.

Thanks

**Comment by parwinderD4D** [comment]
Thanks for your help @ssplugin  :)

**Comment by parwinderD4D** [comment]
Hi Team,

I have successfully imported the categories as well I have created the new field in CSV file e.g assign Categories and set  value [34,563,62] etc and when import data  in the controller I have just called these values under the field handler :

` 
$userfield['categoryAnimalTypes'] =  $fields['assignedCategories'];
if( !empty($userfield) ) { 
       $user->setFieldValues( $userfield );
  }
  $isSaveUser = Craft::$app->getElements()->saveElement($user, false);`
  
  and its save all the categories
  
  Thansk

**Comment by ssplugin** [comment]
@parwinderD4D 
You did it by manually assign values using **id**.  But end-user sometimes does not know block id [**34,563,62**].
We appreciate your work. Thanks

**Comment by parwinderD4D** [comment]
> @parwinderD4D
> You did it by manually assign values using **id**. But end-user sometimes does not know block id [**34,563,62**].
> We appreciate your work. Thanks

Actually, for export data, I just create custom functionality, which helps to export data by following the same format of the plugin CVS file with additional fields **assignedCategories**  where I have to get assigned category list and save there ids in array format [**34,563,62**] and the rest of the work done by plugin import functionality

Thanks

**Comment by ssplugin** [comment]
@parwinderD4D 
If you feel. It is working for the Matrix field properly then you can able to create a pull request or share it with us directly.
It will help other users who are willing to export and import the matrix field.
We will be thankful to you for your contribution. By the way, Have you to buy our plugin license yet, or only used the Trial (Test) version?
